# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Models' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Models

  target 'ModelsTests' do
    # Pods for testing
  end

end

target 'SampleSwiftApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleSwiftApp
  pod 'SwiftLint', '0.39.2'
  pod 'LicensePlist', '2.15.1'
  pod 'R.swift', '5.2.2'

  target 'SampleSwiftAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleSwiftAppUITests' do
    # Pods for testing
  end

end
